[package]
name = "exif"
version = "0.1.0"
edition = "2021"

[dependencies]
gio = "0.20.7"
gtk = { version = "0.9.5", package = "gtk4", features = ["v4_6"] }
img-parts = "0.3.3"
kamadak-exif = "0.6.1"
little_exif = "0.6.2"
rexiv2 = "0.10.0"

